### ISSUE TITLE
Application Error

### ISSUE THREAD

**Issue by agustinbrand** [copilot-is/copilot.is#2]
Hi! I've been using the app for some time and i got this issue on a friends phone that i can't replicate on mine. It's an application error after login in with any Google account in his particular device. I cant seem to replicate the issue

ERRORChunkLoadError: Loading chunk 108 failed. this is in the browser console, it only happens when i use his iPhone 14 Pro Max.

ERRORChunkLoadError: Loading chunk 108 failed.
(missing: https://www.copilot.is/_next/static/chunks/108-597cd5ad19f6d8c7.js)

**Comment by agustinbrand** [comment]
More info in the console:

NotFoundError: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.
    at aZ (71d5b396-67cd7e101fea6d35.js:1:75848)
    at aZ (71d5b396-67cd7e101fea6d35.js:1:75929)
    at a7 (71d5b396-67cd7e101fea6d35.js:1:84024)
    at a5 (71d5b396-67cd7e101fea6d35.js:1:78506)
    at a6 (71d5b396-67cd7e101fea6d35.js:1:78373)
    at a5 (71d5b396-67cd7e101fea6d35.js:1:81025)
    at a6 (71d5b396-67cd7e101fea6d35.js:1:78373)
    at a5 (71d5b396-67cd7e101fea6d35.js:1:78498)
    at a6 (71d5b396-67cd7e101fea6d35.js:1:78373)
    at a5 (71d5b396-67cd7e101fea6d35.js:1:78498)
window.console.error @ 963-a3881321074a5fbe.js:1Understand this error
963-a3881321074a5fbe.js:1 NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at a2 (71d5b396-67cd7e101fea6d35.js:1:76620)
    at a1 (71d5b396-67cd7e101fea6d35.js:1:76044)
    at a2 (71d5b396-67cd7e101fea6d35.js:1:76857)
    at a1 (71d5b396-67cd7e101fea6d35.js:1:76044)
    at a2 (71d5b396-67cd7e101fea6d35.js:1:77133)
    at a1 (71d5b396-67cd7e101fea6d35.js:1:76044)
    at a2 (71d5b396-67cd7e101fea6d35.js:1:77325)
    at a1 (71d5b396-67cd7e101fea6d35.js:1:76044)
    at a2 (71d5b396-67cd7e101fea6d35.js:1:77133)
    at a1 (71d5b396-67cd7e101fea6d35.js:1:76044)
window.console.error @ 963-a3881321074a5fbe.js:1Understand this error
/favicon.ico:1

**Comment by chats-is** [comment]
Try new version.

**Comment by agustinbrand** [comment]
Okay, i'll try it in the problematic devices. Also, it seems a little slower when starting a new chat compared to the old version. Why is that? 

Thanks for all the good work!
